part of 'order_bloc.dart';

@freezed
abstract class OrderState with _$OrderState {
  const factory OrderState({
    required Status getOrderListStatus,
    required List<OrderResponse> ordersList,
    required int totalCount,
    required bool hasMore,
    required bool isLoadingMore,
    required Status paginationStatus,
    required Status getOrderDetailStatus,
    required OrderDetailsResponseModel orderDetails,
    required Status confirmPickupStatus,
    required Status addBagStatus,
    required Status createNewBagStatus,
    required Status getServicesListStatus,
    required Status removeBagStatus,
    required Status moveBagStatus,
    required List<ServiceListDatamodel> servicesList,
    required Status getMyOrderListStatus,
    required List<OrderResponse> myordersList,
    required int myOrdersCount,
     required bool myOrdershasMore,
    required bool myOrdersisLoadingMore,
    required Status myOrderspaginationStatus,
    required Status getCashSettlmentListStatus,
    required List<CashSettlementResponse> cashSettlmentsList,
    required int cashSettlmentsCount,
     required bool cashSettlmentshasMore,
    required bool cashSettlmentsisLoadingMore,
    required Status cashSettlmentspaginationStatus,
  }) = _OrderState;
  factory OrderState.initial() => OrderState(
        getOrderListStatus: Status.initial(),
        ordersList: [],
        hasMore: true,
        isLoadingMore: false,
        paginationStatus: Status.initial(),
        totalCount: 0,
        getOrderDetailStatus: Status.initial(),
        orderDetails:const OrderDetailsResponseModel(),
        confirmPickupStatus: Status.initial(),
        addBagStatus: Status.initial(),
        createNewBagStatus: Status.initial(),
        getServicesListStatus: Status.initial(),
        servicesList: [],
        removeBagStatus: Status.initial(),
        moveBagStatus: Status.initial(),
        getMyOrderListStatus: Status.initial(),
        myordersList: [],
        myOrdersCount: 0,
        myOrdershasMore: true,
        myOrdersisLoadingMore: false,
        myOrderspaginationStatus: Status.initial(),
        getCashSettlmentListStatus: Status.initial(),
        cashSettlmentsList: [],
        cashSettlmentsCount: 0,
        cashSettlmentshasMore: true,
        cashSettlmentsisLoadingMore: false,
        cashSettlmentspaginationStatus: Status.initial()

      );
}
